repos:
  - repo: local
    hooks:
      - id: uv-sync
        name: UV Sync
        entry: bash -c 'uv sync && git add uv.lock'
        language: system
        always_run: true
        pass_filenames: false
        stages: [pre-commit]