repos:
  - repo: local
    hooks:
      - id: uv-sync
        name: UV Sync
        entry: uv sync
        language: system
        always_run: true
        pass_filenames: false
        stages: [pre-commit]