[build-system]
requires = ["setuptools>=80", "wheel"]
build-backend = "setuptools.build_meta"
# requires = ["hatchling"]
# build-backend = "hatchling.build"

[project]
name = "machineconfig"
version = "2.0"
description = "Dotfiles management package"
readme = "README.md"
license = {text = "Apache 2.0"}
authors = [
    {name = "Alex Al-Saffar", email = "programmer@usa.com"},
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.13"
dependencies = [
    "rich>=14.0.0",
    "paramiko>=3.5.1",
    "psutil>=7.0.0",
    "fire>=0.7.0",
    "pydantic>=2.11.3",
    "gitpython>=3.1.44",
    "pyfzf>=0.3.1",
    "rclone-python>=0.1.23",
    "pytz>=2025.2",
    "tomli>=2.2.1",
    "toml>=0.10.2",
    "pyyaml>=6.0.2",
    "pyjson5>=1.6.9",
    "requests>=2.32.5",
    "tqdm>=4.67.1",
    "joblib>=1.5.2",
    "randomname>=0.2.1",
    "cryptography>=44.0.2",
    "tenacity>=9.1.2",
]

[project.optional-dependencies]
windows = [
    "pywin32"
]
# docs extra for documentation generation
docs = [
    "pdoc>=15.0.2"
]

[project.urls]
"Homepage" = "https://github.com/thisismygitrepo/machineconfig"
"Bug Tracker" = "https://github.com/thisismygitrepo/machineconfig/issues"

[tool.setuptools]
package-dir = {"" = "src"}
license-files = []

[tool.setuptools.packages.find]
where = ["src"]

[tool.uv.sources]
crocodile = { path = "../crocodile", editable = true }

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
    "ipython>=9.5.0",
    "mypy>=1.17.1",
    "pudb>=2025.1",
    "pylint>=3.3.8",
    "pyrefly>=0.31.0",
    "pyright>=1.1.404",
    "ty>=0.0.1a20",
    "types-paramiko>=4.0.0.20250822",
    "types-pytz>=2025.2.0.20250809",
    "types-pyyaml>=6.0.12.20250822",
    "types-requests>=2.32.4.20250809",
    "types-toml>=0.10.8.20240310",
]
