[build-system]
requires = ["setuptools>=62", "wheel"]
build-backend = "setuptools.build_meta"
# requires = ["hatchling"]
# build-backend = "hatchling.build"

[project]
name = "machineconfig"
version = "1.96"
description = "Dotfiles management package"
readme = "README.md"
license = {text = "Apache 2.0"}
authors = [
    {name = "Alex Al-Saffar", email = "programmer@usa.com"},
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.11"
dependencies = [
    "crocodile",
    "rich>=14.0.0",
    "paramiko>=3.5.1",
    "psutil>=7.0.0",
    "openai>=1.75.0",
    "nbformat>=5.10.4",
    "fire>=0.7.0",
    "pydantic>=2.11.3",
    "clipboard>=0.0.4",
    "gitpython>=3.1.44",
    "pudb>=2024.1.3",
    "pyfzf>=0.3.1",
    "call-function-with-timeout>=1.1.1",
    "rclone-python>=0.1.23",
]

[project.optional-dependencies]
windows = [
    "pywin32"
]
# docs extra for documentation generation
docs = [
    "pdoc>=15.0.2"
]

[project.urls]
"Homepage" = "https://github.com/thisismygitrepo/machineconfig"
"Bug Tracker" = "https://github.com/thisismygitrepo/machineconfig/issues"

[tool.setuptools]
package-dir = {"" = "src"}
license-files = []

[tool.setuptools.packages.find]
where = ["src"]

[tool.uv.sources]
crocodile = { path = "../crocodile", editable = true }

[dependency-groups]
dev = [
    "rclone-python>=0.1.23",
]
